# Agent Configuration
# https://docs.weave.dev

version: "1.0"

# Optional: define environment variables
env:
  DEFAULT_MODEL: "gemini-2.5-pro"

agents:
  robin:
    model: "gemini-2.5-pro"
    tools:
      - FindFiles
      - GoogleSearch
      - ReadFile
      - ReadFolder
      - ReadManyFiles
      - Save Memory
      - SearchText
      - Shell
      - TodoPause
      - TodoRead
      - TodoWrite
      - WebFetch
      - WriteFile
    config:
      temperature: 0.7
      max_tokens: 10000
