version: "1.0"

# Example using the resources system
# This demonstrates loading prompts, skills, and knowledge from files

agents:
  # Research agent - gathers information
  researcher:
    model: "gpt-4"
    tools:
      - web_search
      - summarizer
    outputs: "research_data"

  # Content writer - uses system prompt and knowledge base
  writer:
    model: "claude-3-opus"
    # Load system prompt from file
    # prompt: "@prompts/content_writer"
    inputs: "researcher"
    tools:
      - markdown_formatter
    # Load knowledge base for brand voice
    # knowledge: ["@knowledge/brand_voice"]
    outputs: "draft_content"

  # SEO optimizer - uses skills
  seo_specialist:
    model: "gpt-4"
    inputs: "writer"
    # Load skills from file
    # skills: ["@skills/seo_optimization"]
    tools:
      - web_search
      - json_parser
    outputs: "optimized_content"

weaves:
  content_pipeline:
    description: "Research, write, and optimize content"
    agents:
      - researcher
      - writer
      - seo_specialist

# Note: Resource loading (@prompts/, @skills/, @knowledge/)
# will be implemented in the agent configuration system in v2.0
# For now, resources can be loaded programmatically:
#
# from weave.resources import ResourceLoader
# loader = ResourceLoader()
# loader.load_all()
# prompt = loader.get_resource(ResourceType.SYSTEM_PROMPT, "content_writer")
