version: "1.0"

# Research Assistant
# Comprehensive research and analysis workflow

env:
  DEFAULT_MODEL: "gpt-4"
  RESEARCH_DEPTH: "comprehensive"

tools:
  academic_search:
    description: "Search academic papers and journals"
    parameters:
      type: "object"
      properties:
        query:
          type: "string"
        year_from:
          type: "integer"
      required: ["query"]

  web_search:
    description: "Search the web"
    parameters:
      type: "object"
      properties:
        query:
          type: "string"
      required: ["query"]

agents:
  literature_reviewer:
    model: "${DEFAULT_MODEL}"
    description: "Review academic literature"
    tools: [academic_search]
    config:
      temperature: 0.5
      max_tokens: 3000
    system_prompt: |
      Conduct thorough literature review:
      - Search relevant papers and studies
      - Summarize key findings
      - Identify research gaps
      - Note methodologies used
      - Cite all sources properly
    outputs: "literature_review"

  data_collector:
    model: "${DEFAULT_MODEL}"
    description: "Collect data and evidence"
    tools: [web_search, academic_search]
    config:
      temperature: 0.3
      max_tokens: 2000
    system_prompt: |
      Gather supporting data:
      - Find statistics and metrics
      - Collect case studies
      - Identify trends and patterns
      - Verify data sources
      - Organize findings systematically
    outputs: "data"

  synthesizer:
    model: "${DEFAULT_MODEL}"
    description: "Synthesize findings into report"
    tools: []
    inputs: "literature_reviewer"
    config:
      temperature: 0.7
      max_tokens: 4000
    system_prompt: |
      Synthesize research into coherent report:
      - Integrate literature review and data
      - Identify key themes and insights
      - Draw evidence-based conclusions
      - Highlight implications
      - Structure as academic report
    outputs: "report"

  peer_reviewer:
    model: "${DEFAULT_MODEL}"
    description: "Review for quality and accuracy"
    tools: [web_search]
    config:
      temperature: 0.2
      max_tokens: 2000
    inputs: "synthesizer"
    system_prompt: |
      Review research report critically:
      - Verify facts and citations
      - Check logical consistency
      - Assess argument strength
      - Identify any biases
      - Suggest improvements
    outputs: "final_report"

weaves:
  full_research:
    description: "Complete research workflow"
    agents:
      - literature_reviewer
      - data_collector
      - synthesizer
      - peer_reviewer

  quick_research:
    description: "Fast research without peer review"
    agents:
      - data_collector
      - synthesizer
